package pe.bhintranet.model.dao.ibatis;

import java.util.Collection;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.bhintranet.model.bean.Usuario;
import pe.bhintranet.model.dao.UsuarioDAO;

public class UsuarioDAOImpl extends SqlMapClientDaoSupport implements UsuarioDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuario
     *
     * @ibatorgenerated Sat Dec 16 16:04:47 GMT 2017
     */
    public UsuarioDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuario
     *
     * @ibatorgenerated Sat Dec 16 16:04:47 GMT 2017
     */
    public int deleteByPrimaryKey(Long codusuario) {
        Usuario key = new Usuario();
        key.setCodusuario(codusuario);
        int rows = getSqlMapClientTemplate().delete("usuario.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuario
     *
     * @ibatorgenerated Sat Dec 16 16:04:47 GMT 2017
     */
    public void insert(Usuario record) {
        getSqlMapClientTemplate().insert("usuario.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuario
     *
     * @ibatorgenerated Sat Dec 16 16:04:47 GMT 2017
     */
    public void insertSelective(Usuario record) {
        getSqlMapClientTemplate().insert("usuario.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuario
     *
     * @ibatorgenerated Sat Dec 16 16:04:47 GMT 2017
     */
    public Usuario selectByPrimaryKey(Long codusuario) {
        Usuario key = new Usuario();
        key.setCodusuario(codusuario);
        Usuario record = (Usuario) getSqlMapClientTemplate().queryForObject("usuario.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuario
     *
     * @ibatorgenerated Sat Dec 16 16:04:47 GMT 2017
     */
    public int updateByPrimaryKeySelective(Usuario record) {
        int rows = getSqlMapClientTemplate().update("usuario.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuario
     *
     * @ibatorgenerated Sat Dec 16 16:04:47 GMT 2017
     */
    public int updateByPrimaryKey(Usuario record) {
        int rows = getSqlMapClientTemplate().update("usuario.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    @Override
    public Usuario selectByLoginName(String loginName) {
        Usuario key = new Usuario();
        key.setLoginname(loginName);
        Usuario record = (Usuario) getSqlMapClientTemplate().queryForObject("usuario.ibatorgenerated_selectByLoginName", key);
        if(record !=null){
            record.setRol("ASESOR");
        }
        return record;
    }    
    
    @Override
    public Collection listar(Usuario record) {

            return  getSqlMapClientTemplate().queryForList("usuario.ibatorgenerated_selectAll", record);
    }
    //    
}