package pe.bhintranet.model.dao;

import java.util.Collection;
import pe.bhintranet.model.bean.Usuario;

public interface UsuarioDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuario
     *
     * @ibatorgenerated Sat Dec 16 16:04:47 GMT 2017
     */
    int deleteByPrimaryKey(Long codusuario);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuario
     *
     * @ibatorgenerated Sat Dec 16 16:04:47 GMT 2017
     */
    void insert(Usuario record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuario
     *
     * @ibatorgenerated Sat Dec 16 16:04:47 GMT 2017
     */
    void insertSelective(Usuario record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuario
     *
     * @ibatorgenerated Sat Dec 16 16:04:47 GMT 2017
     */
    Usuario selectByPrimaryKey(Long codusuario);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuario
     *
     * @ibatorgenerated Sat Dec 16 16:04:47 GMT 2017
     */
    int updateByPrimaryKeySelective(Usuario record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table usuario
     *
     * @ibatorgenerated Sat Dec 16 16:04:47 GMT 2017
     */
    int updateByPrimaryKey(Usuario record);
    
    //personalizado
    public Usuario selectByLoginName(String loginName);
    public Collection listar(Usuario record); 
}